name: Deploy demos
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v2
      - name: Wait for Cloudflare Pages build
        uses: WalshyDev/cf-pages-await@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN_PAGES  }}
          accountId: "4955c8c28610ecabc384d84a20458a53"
          project: "demos"
          # write deplpyment status to github
          githubToken: ${{ secrets.PRIVATE_ACCESS_TOKEN_DEPLOYMENTS }}
